## Compound Classes

Compound classes are datatypes that are composed of other datatypes.
These datatypes are used to represent a collection of numbers, matrices, or entire datasets.

### Atomic Vector

Atomic vectors represent vectors of other datatypes.
You can create vectors using the combine function (`c()`).
In the example below, we create vectors of numerics:

In [28]:
c (1, 2, 3, 4, 5)

[1] 1 2 3 4 5

In [29]:
c(1, 4, 5, -1)

[1]  1  4  5 -1

When creating regular numeric series you can use the colon operator to create expressions that evaluate into numeric vectors.
Using the syntax `b:e`, the series will start at `b` and end at `e`.
It will create an increasing series if $b < e$, and a decreasing series if $b e$.
If $b = e$ it will simply evaluate into one number.

In [30]:
1:5

[1] 1 2 3 4 5

In [31]:
5:-3

[1]  5  4  3  2  1  0 -1 -2 -3

In [32]:
3:3

[1] 3

There are some helpful functions and operations you can use with vectors, you can use `length()`, which evaluates to the number of items in your vector.
For example, `1:5` has five numerics, so the expression below evaluates as such:

In [33]:
length(1:5)

[1] 5

We can also use `is.vector()` to check if an expression evaluates into a vector.
The `is.vector()` function evaluates to `TRUE` if used on a vector and `FALSE` otherwise.

In [34]:
is.vector(1)

[1] TRUE

You can find the sum of all of the elements of a numeric vector using `sum()`:

In [35]:
sum(c(2,4,7,-1))

[1] 12

You can find the largest and smallest values using `max()`, and `min()`:

In [36]:
max(c(2,4,7,-1))

[1] 7

In [37]:
min(c(2,4,7,-1))

[1] -1

We can also fetch the $n$th element of a vector, to do this we use indexing with the syntax `[i]`, a vector expression, followed by an index `[i]`, evaluates to the $i$th element of said vector.
In the example below we can fetch the third item in the vector, which happens to be `-2`

In [38]:
c(3,8,-2,0.1,4)[3]

[1] -2

What happens if you try to fetch index 0? Or index 6? Or index -1?

The vectors we see above are all double vectors.
But R also supports vectors composed of other datatypes.
You can create vectors of integers using the `L` suffix on the elements:

In [39]:
typeof(c(1L, 2L))

[1] "integer"

You can also create vectors of characters:

In [40]:
typeof(c("this", "word"))

[1] "character"

Does R support vectors of vectors? A vector where the elements are also vectors?

### Matrices

Matrices allow us to create 2-dimensional collections.
These are mainly used to represent its namesake in math.
To create one we use the `matrix()` function and provide it with a vector that can be rearranged into a matrix.

In [41]:
matrix(c(1,2,3,4,5,6), nrow = 2)

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

In the example above, we rearrange the vector `c(1,2,3,4,5,6)` into a matrix with two rows using the `nrow = 2`.
Logically, this means that we the matrix created is of size 2x3.
When creating matrix objects using this method, we generally want the vector's size to be compatible with how we want to rearrange it.
In this case since we specify that we want two rows using `nrow = 2`, we must provide a vector where the number of elements are divisible by 2.
When given an incompatible sizes, R will still try to fit your matrix into the desired matrix dimensions but it will repeat the elements of the vector to fill in missing values in the matrix.
R will warn us when this is happening.

In [42]:
matrix(c(1,2,3,4,5,6), nrow = 4)

Warning message in matrix(c(1, 2, 3, 4, 5, 6), nrow = 4):
“data length [6] is not a sub-multiple or multiple of the number of rows [4]”

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    1
[4,] 4    2

In [43]:
matrix(c(9,8,7,6), nrow = 7)

Warning message in matrix(c(9, 8, 7, 6), nrow = 7):
“data length [4] is not a sub-multiple or multiple of the number of rows [7]”

     [,1]
[1,] 9
[2,] 8
[3,] 7
[4,] 6
[5,] 9
[6,] 8
[7,] 7

In [44]:
matrix(c(0,4), nrow = 6)

     [,1]
[1,] 0
[2,] 4
[3,] 0
[4,] 4
[5,] 0
[6,] 4

Note that creating the matrix using `matrix(c(1,2,3,4,5,6), nrow = 2)`, the matrix will be filled up column by column, starting from the first column.
If we want to fill the matrix up by row instead we add the flag `byrow = TRUE` in the function call:

In [45]:
matrix(c(1,2,3,4,5,6), nrow = 2)

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

In [46]:
matrix(c(1,2,3,4,5,6), nrow = 2, byrow = TRUE)

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6

We can also create matrices by specifying the number of columns instead of number of rows.
To do this we simply use `ncols` instead of `nrows`

In [47]:
matrix(c(1,2,3,4,5,6), ncol = 2)

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

In [48]:
matrix(c(1,2,3,4,5,6), ncol = 2, byrow = TRUE)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

We can isolate elements of a matrix using indexing.
Using the indexing syntax for vectors `m[i]`, you will retrieve the ith element if the matrix was unfurled into a vector by column:

In [49]:
m = matrix(c(1,2,3,4,5,6), ncol = 2)
m

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

We can also retrieve an element by specifying the row and column number.
For example we can retrieve the element found at the 3rd row and 1st column using the following syntax:

In [50]:
m[3,1]

[1] 3

We can also retrieve an entire row (specifically the 2nd row), using the following syntax:

In [51]:
m[2,]

[1] 2 5

Likewise, the second column can be retrieved as such:

In [52]:
m[,2]

[1] 4 5 6

# Attributes


There are more compound types in R.
But before we talk about other compound types, lets talk about R attributes.
R allows us to assign metadata to any object using attributes.
While you can use this on any valid object, it's usefulness becomes more obvious once you are working with compound classes.

## `name` attribute

For example, if you want to assign specific names to the elements of a vector object, you can use the special `name` attribute using the following syntax:

In [53]:
vec <- c(23, 21, 22, 22, 18, 90)
names(vec) <- c("first", "second", "third", "fourth", "fifth", "sixth")
vec

 first second  third fourth  fifth  sixth
    23     21     22     22     18     90

In [54]:
vec["second"]

second
    21

Attributes are considered like metadata because attributes do not affect the actual values of the data itself.
In the example above we are simply assigning names to the elements of our numeric vector `vec`.
With names assigned, when `vec` is evaluated by the REPL, the value does not change but the it is displayed has changed.
The names of every element is also displayed alongside their values.
It also allows us to use the names as indexes as shown by the evaluation of `vec["second"]` above.

## `dim` attribute

The `dim` attribute refers to the dimensions of an object. 
In the example below, we can check the dimensions of the matrix called `identity` using `dim(identity)`:

In [55]:
identity = matrix(c(1,0,0,1), nrow = 2)
identity

     [,1] [,2]
[1,] 1    0
[2,] 0    1

In [56]:
dim(identity)

[1] 2 2

The `dim` attribute also allow you to change the dimensions of a matrix.
Below `mat` is originally a $3 \times 2$. We can change it to $1 \times 6$ by reassigning the dim attribute.

In [57]:
mat = matrix(c(1:6), nrow = 3)
mat

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

In [58]:
dim(mat)

[1] 3 2

In [59]:
dim(mat) <- c(1,6)

Vectors do not have a dim attribute. If you try to display the dimension of a vector using `dim()`, it will evaluate into `NULL`.
But if you assign the `dim` of a vector, it will convert the vector into a matrix based on the specified dimensions.

In [60]:
vec = c(1:6)
dim(vec)

NULL

In [61]:
dim(vec) <- c(2,3)
vec

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

## `class` attribute

The `class` attribute refers to the high-level classification of an R object.
For example, we've been using this attribute to show if an object is a matrix.

In [62]:
mat = matrix(c(1:6), nrow = 3)
class(mat)

[1] "matrix" "array"

In the example above, we can see that `mat` has two classes, matrix and array.
This is as expected because all matrices are arrays.
It's out of scope for this discussion but this is an example of inheritance.

Just like, `dim` and `name` you can change the `class` attribute using `<-` assignment.

In [63]:
numbers = c("1", "-2", "1000")
numbers

[1] "1"    "-2"   "1000"

In [64]:
class(numbers) <- "numeric"
numbers

[1]    1   -2 1000

While the example above, works to convert values into different types, said method is considered bad practice.
To make sure that you are performing type/class coercions safely, you can use the `as` conversions instead.

In [65]:
numbers = c("1", "-2", "1000")
numbers <- as.numeric(numbers)
numbers

[1]    1   -2 1000

There are more attributes aside from `names`, `dim`, and class `class`.
Some of these attributes are specific to the class only.
For example, matrices can use the `colnames`, and `rownames` attributes.

In [66]:
table = matrix(c(1:9), nrow = 3)
rownames(table) <- c("top", "middle", "bottom")
colnames(table) <- c("left", "center", "right")
table

       left center right
top    1    4      7
middle 2    5      8
bottom 3    6      9

In [67]:
table["top","right"]

[1] 7

To show all attributes with assigned values, you can use `attributes()`:

In [68]:
attributes(table)

$dim
[1] 3 3

$dimnames
$dimnames[[1]]
[1] "top"    "middle" "bottom"

$dimnames[[2]]
[1] "left"   "center" "right"

Note that `rownames` is just internally translated to `dimnames[[1]]` and `colnames` to `dimnames[[2]]`.
The attribute `dimnames` refers to dimension names, a generalization of row names, column names, and etc.

# More compound classes

Some more compound classes that you might encounter in R include `array`s which are just like matrices but can support more than two dimensions.
For example, the array below has a size of $3 \times 2 \times 4$.
You can think of it as 4 layers of $3 \times 2$ matrices

In [69]:
array(1:24, dim = c(3,2,4))

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

, , 3

     [,1] [,2]
[1,]   13   16
[2,]   14   17
[3,]   15   18

, , 4

     [,1] [,2]
[1,]   19   22
[2,]   20   23
[3,]   21   24

Another compound class is the `list`.
You can think of it as a generalized version of a vector.
While the elements of a vector can only be homogeneous simple types, `list`s can support a mix of classes classes (including compound classes).

In [70]:
list(3, "word", TRUE, c(0,1,2), matrix(c(1,2), nrow = 1), list("a", 2))

[[1]]
[1] 3

[[2]]
[1] "word"

[[3]]
[1] TRUE

[[4]]
[1] 0 1 2

[[5]]
     [,1] [,2]
[1,]    1    2

[[6]]
[[6]][[1]]
[1] "a"

[[6]][[2]]
[1] 2

# Data Frames

Data frames are compound classes that you will for sure encounter a lot as a data scientist.
Data frames are used to represent tabular data.
Like any table, a data frame is two dimensional.
But unlike matrices, or 2-dimensional arrays, the columns of a data frame can be of non-numeric.
Each column can be vectors of any simple type.
In the example below from the sample dataset `iris`, the first four columns are numeric vectors, and the last column is a character vector.

In [71]:
head(iris)

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

Note that `head()` is a function that we use to display only the first few rows of a dataframe.
If we don't use it, it will display all rows of the dataset which can be too long.

As we can see in the example above, data frames also have helpful attributes such as the column names also known as headers, represented by the attribute `names`.
Row numbers are represented by the attribute `row.names`

In [72]:
attributes(iris)

$names
[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

$class
[1] "data.frame"

$row.names
  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150

You can fetch elements from the data frame the same way you do for matrices. Entire rows:

In [1]:
iris[20,]

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
20 5.1          3.8         1.5          0.3         setosa

Entire columns:

In [74]:
iris[,2]

  [1] 3.5 3.0 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.0 3.0 4.0 4.4 3.9 3.5
 [19] 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.0 3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 [37] 3.5 3.6 3.0 3.4 3.5 2.3 3.2 3.5 3.8 3.0 3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 [55] 2.8 2.8 3.3 2.4 2.9 2.7 2.0 3.0 2.2 2.9 2.9 3.1 3.0 2.7 2.2 2.5 3.2 2.8
 [73] 2.5 2.8 2.9 3.0 2.8 3.0 2.9 2.6 2.4 2.4 2.7 2.7 3.0 3.4 3.1 2.3 3.0 2.5
 [91] 2.6 3.0 2.6 2.3 2.7 3.0 2.9 2.9 2.5 2.8 3.3 2.7 3.0 2.9 3.0 3.0 2.5 2.9
[109] 2.5 3.6 3.2 2.7 3.0 2.5 2.8 3.2 3.0 3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
[127] 2.8 3.0 2.8 3.0 2.8 3.8 2.8 2.8 2.6 3.0 3.4 3.1 3.0 3.1 3.1 3.1 2.7 3.2
[145] 3.3 3.0 2.5 3.0 3.4 3.0

Note that when fetching an entire column, you might accidentally interchange `iris[,2]` and `iris[2]`.
While both look the same and are related, the former evaluates into a vector, while the latter evaluates into a data frame with one column (specifically the second column).
In some cases, some expressions might require a data frame and in some cases expressions might require the vector itself.

Selected rows and columns:

In [75]:
iris[25:30,1:2]

   Sepal.Length Sepal.Width
25 4.8          3.4
26 5.0          3.0
27 5.0          3.4
28 5.2          3.5
29 5.2          3.4
30 4.7          3.2

Or a single cell:

In [76]:
iris[26,3]

[1] 1.6

But since data frames usually come with useful attributes such as headers and row names, you can forgo indices and use said headers and row names instead.
In the example below, instead of using `iris[25:30,1:2]`, you can write the following:

In [77]:
iris[25:30,c("Sepal.Length","Sepal.Width")]

   Sepal.Length Sepal.Width
25 4.8          3.4
26 5.0          3.0
27 5.0          3.4
28 5.2          3.5
29 5.2          3.4
30 4.7          3.2

In the case of the `iris` dataset (and most datasets), row indices and row names are the same.

If you are familiar with relational databases, you can perform also selections, joins, unions and intersections with data frames.
The example below demonstrates a selection operation (\sigma) that filters only rows that have a sepal length less than 5:

In [78]:
iris[iris["Sepal.Length"] < 5,]

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
7   4.6          3.4         1.4          0.3         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
23  4.6          3.6         1.0          0.2         setosa
25  4.8          3.4         1.9          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
31  4.8          3.1         1.6          0.2         setosa
35  4.9          3.1         1.5          0.2         setosa
38  4.9          3.6         1.4          0.1         setosa
39  4.4          3.0         1.3          0.2         setosa
42  4.5          2.3         1.3          0.3         setosa
43  4.4          3.2         1.3          0.2         setosa
46  4.8          3.0         1.4          0.3         setosa
48  4.6          3.2         1.4          0.2         setosa
58  4.9          2.4         3.3          1.0         versicolor
107 4.9          2.5         4.5          1.7         virginica

You can also perform aggregations on the data frame.
In the example below we can find the mean of all sepal widths for all rows:

In [3]:
mean(iris[,"Sepal.Width"], na.rm = TRUE)

[1] 3.057333

`na.rm = TRUE` is a flag that must be set to TRUE so that columns with NA values are not a automatically aggregated to NA.

You can combine these principles to find the mean of sepal width of species labelled as "setosa"

In [80]:
mean(iris[iris["Species"] == "setosa",][,"Sepal.Width"], na.rm = TRUE)

[1] 3.428

You can also perform aggregations with specified groupings.
In the example below, sepal width and sepal length are aggregated using mean, grouped by species:

In [81]:
aggregate(cbind(Sepal.Width,Sepal.Length) ~ Species, data = iris, FUN = mean)

  Species    Sepal.Width Sepal.Length
1 setosa     3.428       5.006
2 versicolor 2.770       5.936
3 virginica  2.974       6.588